require('seneca')()
.use('basic')
.use('entity')
.use('stats')
//.use('seneca-repl', {port: 10022})
.listen({ type: 'tcp', port:9003, pin:'role:stats,info:dt' })
.listen({ type: 'tcp', port:9004, pin:'role:stats' })
