require('seneca')()
.use('basic')
.use('entity')
.use('dt.js')
//.use('seneca-repl', {port: 10021})
.listen({ type: 'tcp', pin: 'role:dt' })
.client({ type: 'tcp', port:9003, pin:'role:stats,info:dt' })
