require('seneca')()
.use('basic')
.use('entity')
.use('dt')
//.use('seneca-repl', {port: 10021})
.listen({ type: 'tcp', port: 9002, pin: 'role:dt' })
.client({ type: 'tcp', port:9003, pin:'role:stats,info:dt' })
.client({ type: 'tcp', port: 9005, pin: 'role:engine' })
